general:
  database: posts.db

chat_gpt:
  api_key: key

xml_rpc:
  rpc_url: url
  rpc_user: user_name
  rpc_password: password

telegram:
  tele_token: token
  tele_channel: chanel_id

facebook:
  fb_page: fb_page_url
  fb_user: user
  fb_password: password